// <auto-generated />
using System;
using System.Collections.Generic;
using MarketOurs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketOurs.Data.Migrations
{
    [DbContext(typeof(MarketContext))]
    [Migration("20260404135706_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CommentModelUserModel", b =>
                {
                    b.Property<string>("LikeCommentsId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LikeUsersId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("LikeCommentsId", "LikeUsersId");

                    b.HasIndex("LikeUsersId");

                    b.ToTable("CommentModelUserModel");
                });

            modelBuilder.Entity("CommentModelUserModel1", b =>
                {
                    b.Property<string>("DislikeUsersId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DislikesCommentsId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("DislikeUsersId", "DislikesCommentsId");

                    b.HasIndex("DislikesCommentsId");

                    b.ToTable("CommentModelUserModel1");
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.CommentModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dislikes")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("ParentCommentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.PostModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Dislikes")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Images")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Watch")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PostModelUserModel", b =>
                {
                    b.Property<string>("LikePostsId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LikeUsersId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("LikePostsId", "LikeUsersId");

                    b.HasIndex("LikeUsersId");

                    b.ToTable("PostModelUserModel");
                });

            modelBuilder.Entity("PostModelUserModel1", b =>
                {
                    b.Property<string>("DislikeUsersId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DislikesPostsId")
                        .HasColumnType("character varying(64)");

                    b.HasKey("DislikeUsersId", "DislikesPostsId");

                    b.HasIndex("DislikesPostsId");

                    b.ToTable("PostModelUserModel1");
                });

            modelBuilder.Entity("CommentModelUserModel", b =>
                {
                    b.HasOne("MarketOurs.Data.DataModels.CommentModel", null)
                        .WithMany()
                        .HasForeignKey("LikeCommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketOurs.Data.DataModels.UserModel", null)
                        .WithMany()
                        .HasForeignKey("LikeUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommentModelUserModel1", b =>
                {
                    b.HasOne("MarketOurs.Data.DataModels.UserModel", null)
                        .WithMany()
                        .HasForeignKey("DislikeUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketOurs.Data.DataModels.CommentModel", null)
                        .WithMany()
                        .HasForeignKey("DislikesCommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.CommentModel", b =>
                {
                    b.HasOne("MarketOurs.Data.DataModels.CommentModel", "ParentComment")
                        .WithMany("Comments")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MarketOurs.Data.DataModels.PostModel", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketOurs.Data.DataModels.UserModel", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.PostModel", b =>
                {
                    b.HasOne("MarketOurs.Data.DataModels.UserModel", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostModelUserModel", b =>
                {
                    b.HasOne("MarketOurs.Data.DataModels.PostModel", null)
                        .WithMany()
                        .HasForeignKey("LikePostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketOurs.Data.DataModels.UserModel", null)
                        .WithMany()
                        .HasForeignKey("LikeUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PostModelUserModel1", b =>
                {
                    b.HasOne("MarketOurs.Data.DataModels.UserModel", null)
                        .WithMany()
                        .HasForeignKey("DislikeUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketOurs.Data.DataModels.PostModel", null)
                        .WithMany()
                        .HasForeignKey("DislikesPostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.CommentModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.PostModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MarketOurs.Data.DataModels.UserModel", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
